# 网站的基本信息
site:
  tab:  雨霖铃慢 # 浏览器标签栏上显示的文本
  title: 🌵 雨霖铃慢 # 网站的标题
  description: 过得到自己过得到人 # 网站的描述，用于SEO等
  language: zh # 网站的语言，例如 "en" 是英文
  favicon: /favicon.ico # 网站的图标，用于浏览器标签栏和其他地方显示
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: retro # 主题的浅色模式
    dark: coffee # 主题的深色模式
    code: catppuccin-latte # 代码块的主题 https://shiki.style/themes
  date_format: YYYY-MM-DD # 日期格式设置，支持自定义格式
  menu: # 菜单配置
    - id: home # 菜单项的唯一标识符
      text: 主页 # 菜单项显示的文本
      href: / # 菜单项链接的地址
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: 关于
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: posts
      text: 博客
      href: /posts
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: 全部博客
          href: /posts
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: 周而复始
          text: 周而复始
          href: /posts/category/周而复始
          svg: "material-symbols:deployed-code-outline"
          target: _self
        - id: 书影音游
          text: 书影音游
          href: /posts/category/书影音游
          svg: "material-symbols:earthquake-rounded"
          target: _self
        - id: 一技之长
          text: 一技之长
          href: /posts/category/一技之长
          svg: "material-symbols:deployed-code-outline"
          target: _self
        - id: 岁月留痕
          text: 岁月留痕
          href: /posts/category/岁月留痕
          svg: "material-symbols:earthquake-rounded"
          target: _self
        - id: 侃侃而谈
          text: 侃侃而谈
          href: /posts/category/侃侃而谈
          svg: "material-symbols:earthquake-rounded"
          target: _self
        # 子菜单项配置
    - id: gallery
      text: 相册
      href: /gallery
      svg: "material-symbols:photo-library-outline-rounded"
      target: _self
    - id: friend
      text: 友链
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self

# 用户的个人信息
user:
  name: 绫里龙一 # 用户名
  site: "https://www.linglilongyi.com" # 用户的网站链接
  avatar: /profile.png # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      - href: "https://github.com/linglilongyi"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://app.follow.is/share/feeds/99665172360284160"
        ariaLabel: follow
        title: Follow
        svg: "ri:rss-fill"

  footer:
    social:
      - href: "https://github.com/linglilongyi"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://app.follow.is/share/feeds/99665172360284160"
        ariaLabel: follow
        title: Follow
        svg: "ri:rss-fill"
